### ISSUE TITLE
The official Todo list

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/Linux-Fake-Background-Webcam#153]
This is the list of things that I would like to do with this project, in the order of priority.

- [ ] Replace Dockerfile with Python venv.
- [ ] Add configuration file support.
- [ ] Switch the webcam source on the fly.
- [ ] Write a simple GUI.
